import pandas as pd
import matplotlib.pyplot as plt

results = pd.read_csv("weed_training/rtx4090_yolo11m/results.csv")

plt.figure()
plt.plot(results['epoch'], results['metrics/mAP50'], label='mAP@0.5')
plt.plot(results['epoch'], results['metrics/mAP50-95'], label='mAP@0.5:0.95')
plt.xlabel("Epoch")
plt.ylabel("mAP")
plt.legend()
plt.title("mAP vs Epoch")
plt.savefig("mAP_curve.png")
plt.show()

plt.figure()
plt.plot(results['epoch'], results['metrics/precision'], label='Precision')
plt.plot(results['epoch'], results['metrics/recall'], label='Recall')
plt.xlabel("Epoch")
plt.ylabel("Score")
plt.legend()
plt.title("Precision & Recall vs Epoch")
plt.savefig("PR_epoch_curve.png")
plt.show()

plt.figure()
plt.plot(results['epoch'], results['train/box_loss'], label='Box Loss')
plt.plot(results['epoch'], results['train/cls_loss'], label='Cls Loss')
plt.plot(results['epoch'], results['train/dfl_loss'], label='DFL Loss')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Training Loss")
plt.savefig("loss_curve.png")
plt.show()
